### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
What is your intent: Making Readme.md much cleaner and nicer to look at 

What did you change: Readme.md

Does it work: Well, yeah. It's a Readme

Does it cause bugs: None. 

Does it have any other side effect: No, unless you called readme's to have a side effect on your shaders.

Whatever you think of as necessary to tell about it: Easier for new users to navigate to the mirror in case website is down

### CODE REVIEW

**Comment by rre36** [comment]
I guess this isn't a bad thing tbh, gonna merge as it seems useful :p

**Comment by ghost** [comment]
Yay! Thanks.

**Comment by ghost** [comment]
Although, I'd want to give one suggestion. The website is hosted on gitpages. If gitpages goes down, so does GitHub. Would suggest you either host a mirror on gitgud, or someother open source git website

**Comment by rre36** [comment]
Nah the website is now on a dedicated hoster, the github pages are merely redirects to catch the traffic thats going to the old urls.
I am thinking of also hosting downloads on my website tho, for the rare case that github and curseforge are down, or for ease of management.

**Comment by ghost** [comment]
Ah, makes sense. Instead of hosting on your website, why not try hosting a official torrent? They'll never go down, and anyone who knows how to use a torrent client will be able to help you out.

**Pull request merged**
